# Generated by Django 4.2.7 on 2025-07-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='ships_amount_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ships_amount_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ships_amount_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='ships_amount_4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questiontype'),
        ),
    ]
