# Generated by Django 4.2.7 on 2025-07-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_questiontype_settings_ships_amount_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Battlefield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_coord', models.CharField(max_length=255, null=True)),
                ('battleship1_coord', models.CharField(max_length=255, null=True)),
                ('battleship2_coord', models.CharField(max_length=255, null=True)),
                ('cruiser1_coord', models.CharField(max_length=255, null=True)),
                ('cruiser2_coord', models.CharField(max_length=255, null=True)),
                ('cruiser3_coord', models.CharField(max_length=255, null=True)),
                ('destroyer1_coord', models.CharField(max_length=255, null=True)),
                ('destroyer2_coord', models.CharField(max_length=255, null=True)),
                ('destroyer3_coord', models.CharField(max_length=255, null=True)),
                ('destroyer4_coord', models.CharField(max_length=255, null=True)),
                ('patrol1_coord', models.CharField(max_length=255, null=True)),
                ('patrol2_coord', models.CharField(max_length=255, null=True)),
                ('patrol3_coord', models.CharField(max_length=255, null=True)),
                ('patrol4_coord', models.CharField(max_length=255, null=True)),
                ('patrol5_coord', models.CharField(max_length=255, null=True)),
                ('surprise_coord', models.CharField(max_length=255, null=True)),
                ('doublebarrel_coord', models.CharField(max_length=255, null=True)),
                ('reverse1_coord', models.CharField(max_length=255, null=True)),
                ('reverse2_coord', models.CharField(max_length=255, null=True)),
                ('move5_coord', models.CharField(max_length=255, null=True)),
                ('move3_coord', models.CharField(max_length=255, null=True)),
                ('karaoke1_coord', models.CharField(max_length=255, null=True)),
                ('karaoke2_coord', models.CharField(max_length=255, null=True)),
                ('change1_coord', models.CharField(max_length=255, null=True)),
                ('change2_coord', models.CharField(max_length=255, null=True)),
                ('bonus1_coord', models.CharField(max_length=255, null=True)),
                ('bonus3_coord', models.CharField(max_length=255, null=True)),
                ('bonus5_coord', models.CharField(max_length=255, null=True)),
                ('penalty1_coord', models.CharField(max_length=255, null=True)),
                ('penalty3_coord', models.CharField(max_length=255, null=True)),
                ('penalty5_coord', models.CharField(max_length=255, null=True)),
                ('song_coord', models.CharField(max_length=255, null=True)),
                ('echo_coord', models.CharField(max_length=255, null=True)),
                ('even_coord', models.CharField(max_length=255, null=True)),
                ('special_coord', models.CharField(max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.game')),
            ],
        ),
    ]
