# Generated by Django 4.2.7 on 2025-07-10 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_answer_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('game', models.CharField(max_length=255, null=True)),
                ('image_link', models.CharField(max_length=255, null=True)),
                ('audio_link', models.CharField(max_length=255, null=True)),
                ('video_link', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_active', models.IntegerField()),
                ('used', models.IntegerField()),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questiontype')),
            ],
        ),
    ]
