# Generated by Django 4.2.7 on 2025-07-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_drawquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='draw',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DrawQuestion',
        ),
    ]
