# Generated by Django 4.2.7 on 2025-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_draw_delete_drawquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlefield',
            name='revealed_water',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
