# Generated by Django 4.2.7 on 2025-07-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_battlefield_revealed_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlefield',
            name='revealed_water',
            field=models.TextField(null=True),
        ),
    ]
