# Generated by Django 4.2.7 on 2025-07-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_round_number_results_bonus_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
