# Generated by Django 4.2.7 on 2025-07-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_answer_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='round',
            new_name='checked',
        ),
    ]
