# Generated by Django 4.2.7 on 2025-07-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_round_useranswer_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='checked',
            field=models.FloatField(null=True),
        ),
    ]
