# Generated by Django 4.2.7 on 2025-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_useranswer_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='order',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
