# Generated by Django 4.2.7 on 2025-08-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_queue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='current',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
