# Generated by Django 4.2.7 on 2025-09-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_queue_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='o_number',
            field=models.IntegerField(null=True),
        ),
    ]
