# Generated by Django 4.2.7 on 2025-09-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_settings_language_settings_o_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='ships_amount_1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='ships_amount_2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='ships_amount_3',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='ships_amount_4',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='size',
        ),
    ]
