# Generated by Django 4.2.7 on 2025-09-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_settings_ships_amount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='special',
            field=models.IntegerField(null=True),
        ),
    ]
