# Generated by Django 4.2.7 on 2025-09-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_settings_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='commands',
            name='admin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
