# Generated by Django 4.2.7 on 2025-11-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='special',
        ),
    ]
