# Generated by Django 4.2.7 on 2025-11-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_settings_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=255, null=True)),
                ('uz', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
